common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: findyourgig_development

test:
  <<: *common
  database: findyourgig_test

production:
  <<: *common
  database: findyourgig_production