require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GigsController do

  # This should return the minimal set of attributes required to create a valid
  # Gig. As you add validations to Gig, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GigsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gigs as @gigs" do
      gig = Gig.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gigs).should eq([gig])
    end
  end

  describe "GET show" do
    it "assigns the requested gig as @gig" do
      gig = Gig.create! valid_attributes
      get :show, {:id => gig.to_param}, valid_session
      assigns(:gig).should eq(gig)
    end
  end

  describe "GET new" do
    it "assigns a new gig as @gig" do
      get :new, {}, valid_session
      assigns(:gig).should be_a_new(Gig)
    end
  end

  describe "GET edit" do
    it "assigns the requested gig as @gig" do
      gig = Gig.create! valid_attributes
      get :edit, {:id => gig.to_param}, valid_session
      assigns(:gig).should eq(gig)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gig" do
        expect {
          post :create, {:gig => valid_attributes}, valid_session
        }.to change(Gig, :count).by(1)
      end

      it "assigns a newly created gig as @gig" do
        post :create, {:gig => valid_attributes}, valid_session
        assigns(:gig).should be_a(Gig)
        assigns(:gig).should be_persisted
      end

      it "redirects to the created gig" do
        post :create, {:gig => valid_attributes}, valid_session
        response.should redirect_to(Gig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gig as @gig" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gig.any_instance.stub(:save).and_return(false)
        post :create, {:gig => { "name" => "invalid value" }}, valid_session
        assigns(:gig).should be_a_new(Gig)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gig.any_instance.stub(:save).and_return(false)
        post :create, {:gig => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gig" do
        gig = Gig.create! valid_attributes
        # Assuming there are no other gigs in the database, this
        # specifies that the Gig created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gig.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => gig.to_param, :gig => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested gig as @gig" do
        gig = Gig.create! valid_attributes
        put :update, {:id => gig.to_param, :gig => valid_attributes}, valid_session
        assigns(:gig).should eq(gig)
      end

      it "redirects to the gig" do
        gig = Gig.create! valid_attributes
        put :update, {:id => gig.to_param, :gig => valid_attributes}, valid_session
        response.should redirect_to(gig)
      end
    end

    describe "with invalid params" do
      it "assigns the gig as @gig" do
        gig = Gig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gig.any_instance.stub(:save).and_return(false)
        put :update, {:id => gig.to_param, :gig => { "name" => "invalid value" }}, valid_session
        assigns(:gig).should eq(gig)
      end

      it "re-renders the 'edit' template" do
        gig = Gig.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gig.any_instance.stub(:save).and_return(false)
        put :update, {:id => gig.to_param, :gig => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gig" do
      gig = Gig.create! valid_attributes
      expect {
        delete :destroy, {:id => gig.to_param}, valid_session
      }.to change(Gig, :count).by(-1)
    end

    it "redirects to the gigs list" do
      gig = Gig.create! valid_attributes
      delete :destroy, {:id => gig.to_param}, valid_session
      response.should redirect_to(gigs_url)
    end
  end

end
